%YAML 1.2
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
name: sync
components:
- name: left_image_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: left_image_receiver
    min_size: 1
- name: right_image_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: right_image_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- name: left_cam_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: left_cam_receiver
    min_size: 1
- name: right_cam_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: right_cam_receiver
    min_size: 1
- type: nvidia::isaac_ros::Synchronization
  parameters:
    left_image_input: left_image_receiver
    right_image_input: right_image_receiver
    left_cam_input: left_cam_receiver
    right_cam_input: right_cam_receiver
    left_image_output: left_image_transmitter
    right_image_output: right_image_transmitter
    left_cam_output: left_cam_transmitter
    right_cam_output: right_cam_transmitter
    inputs: [left_image_receiver, right_image_receiver, left_cam_receiver, right_cam_receiver]
    outputs: [left_image_transmitter, right_image_transmitter, left_cam_transmitter, right_cam_transmitter]
- name: left_image_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: left_image_transmitter
    min_size: 1
- name: right_image_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: right_image_transmitter
    min_size: 1
- name: left_cam_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: left_cam_transmitter
    min_size: 1
- name: right_cam_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: right_cam_transmitter
    min_size: 1
---
name: disparity
components:
- name: data_receiver_left
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver_left
    min_size: 1
- name: data_receiver_right
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver_right
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: pool
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 22118400
    num_blocks: 40
- type: nvidia::isaac::SGMDisparity
  parameters:
    left_image_name: "left_image"
    right_image_name: "right_image"
    output_name: "disparity"
    pool: pool
    left_image_receiver: data_receiver_left
    right_image_receiver: data_receiver_right
    output_transmitter: data_transmitter
    min_disparity: 0
    max_disparity: 64
    backends: "CUDA"
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: pool
    min_blocks: 1
---
name: left_camera_info_broadcaster
components:
- type: nvidia::gxf::Broadcast
  parameters:
    source: camera_info_in
- name: camera_info_in
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: camera_info_in
    min_size: 1
- name: left_camera_info_out_1
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: left_camera_info_out_1
    min_size: 1
- name: left_camera_info_out_2
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: left_camera_info_out_2
    min_size: 1
---
name: right_camera_info_broadcaster
components:
- type: nvidia::gxf::Broadcast
  parameters:
    source: camera_info_in
- name: camera_info_in
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: camera_info_in
    min_size: 1
- name: right_camera_info_out_1
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: right_camera_info_out_1
    min_size: 1
- name: right_camera_info_out_2
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: right_camera_info_out_2
    min_size: 1
---
name: left_camera_message_compositor
components:
- name: video_buffer_input
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: video_buffer_input
    min_size: 1
- name: camera_model_input
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: camera_model_input
    min_size: 1
- name: camera_message_output
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: camera_message_output
    min_size: 1
- name: left_camera_message_compositor
  type: nvidia::isaac::CameraMessageCompositor
  parameters:
    video_buffer_input: video_buffer_input
    camera_model_input: camera_model_input
    camera_message_output: camera_message_output
---
name: right_camera_message_compositor
components:
- name: video_buffer_input
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: video_buffer_input
    min_size: 1
- name: camera_model_input
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: camera_model_input
    min_size: 1
- name: camera_message_output
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: camera_message_output
    min_size: 1
- name: right_camera_message_compositor
  type: nvidia::isaac::CameraMessageCompositor
  parameters:
    video_buffer_input: video_buffer_input
    camera_model_input: camera_model_input
    camera_message_output: camera_message_output
---
name: egress
components:
- name: disparity_in
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 2
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: disparity_in
    min_size: 1
- name: left_cam_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 2
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: left_cam_receiver
    min_size: 1
- name: right_cam_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 2
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: right_cam_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- type: nvidia::isaac::DisparityCompositor
  parameters:
    left_camera_model_receiver: left_cam_receiver
    right_camera_model_receiver: right_cam_receiver
    disparity_receiver: disparity_in
    output_transmitter: data_transmitter
    min_disparity: 0
    max_disparity: 64
---
name: sink
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
name: connections
components:
- name: connection_1
  type: nvidia::gxf::Connection
  parameters:
    source: sync/left_cam_transmitter
    target: left_camera_info_broadcaster/camera_info_in
- name: connection_2
  type: nvidia::gxf::Connection
  parameters:
    source: sync/right_cam_transmitter
    target: right_camera_info_broadcaster/camera_info_in
- name: connection_3
  type: nvidia::gxf::Connection
  parameters:
    source: left_camera_message_compositor/camera_message_output
    target: disparity/data_receiver_left
- name: connection_4
  type: nvidia::gxf::Connection
  parameters:
    source: right_camera_message_compositor/camera_message_output
    target: disparity/data_receiver_right
- name: connection_5
  type: nvidia::gxf::Connection
  parameters:
    source: sync/left_image_transmitter
    target: left_camera_message_compositor/video_buffer_input
- name: connection_6
  type: nvidia::gxf::Connection
  parameters:
    source: left_camera_info_broadcaster/left_camera_info_out_1
    target: left_camera_message_compositor/camera_model_input
- name: connection_7
  type: nvidia::gxf::Connection
  parameters:
    source: sync/right_image_transmitter
    target: right_camera_message_compositor/video_buffer_input
- name: connection_8
  type: nvidia::gxf::Connection
  parameters:
    source: right_camera_info_broadcaster/right_camera_info_out_1
    target: right_camera_message_compositor/camera_model_input
- name: connection_9
  type: nvidia::gxf::Connection
  parameters:
    source: left_camera_info_broadcaster/left_camera_info_out_2
    target: egress/left_cam_receiver
- name: connection_10
  type: nvidia::gxf::Connection
  parameters:
    source: right_camera_info_broadcaster/right_camera_info_out_2
    target: egress/right_cam_receiver
- name: connection_11
  type: nvidia::gxf::Connection
  parameters:
    source: disparity/data_transmitter
    target: egress/disparity_in
- name: connection_12
  type: nvidia::gxf::Connection
  parameters:
    source: egress/data_transmitter
    target: sink/signal
---
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::MultiThreadScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
    check_recession_period_ms: 1
    worker_thread_number: 2
- type: nvidia::gxf::JobStatistics
  parameters:
    clock: clock